/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Connector.Conexion;
import Model.Patient;
import Toaster.Toaster;
import java.sql.*;
import java.io.ByteArrayInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenov
 */
public class FormPatients extends javax.swing.JInternalFrame {

    private ByteArrayInputStream huellaPaciente;
    Integer sizeHuella;
    boolean isOpen = false;
    boolean tipoQuery = false;
    Toaster toaster;
    int id_paciente;
    DefaultTableModel modt;
    Patient p = new Patient();
  
   

    public FormPatients() {
        setQueryInsert();
        initComponents();
        //  emptyFields();
        disableButtons(false, true, true);
        modt = (DefaultTableModel) tableP.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdPaciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombrePaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoPaciente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFNacimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCNacimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDNacimiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTipoDoc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmailPaciente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRH = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        comboGestante = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboEtnia = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtFCreacion = new javax.swing.JTextField();
        btnSaveP = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        btnAssociate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnNewP = new javax.swing.JButton();
        btnIdentify = new javax.swing.JButton();
        btnSearchUpdateP = new javax.swing.JButton();
        btnDeleteP = new javax.swing.JButton();
        txtPYDT = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableP = new javax.swing.JTable();

        setBackground(new java.awt.Color(37, 51, 61));
        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gestión de Pacientes");
        setMinimumSize(new java.awt.Dimension(800, 450));

        jPanel1.setBackground(new java.awt.Color(37, 51, 61));

        jPanel2.setBackground(new java.awt.Color(37, 51, 61));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 216, 158), 1, true));
        jPanel2.setToolTipText("");
        jPanel2.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 216, 158));
        jLabel1.setText("ID Paciente");

        txtIdPaciente.setEditable(false);
        txtIdPaciente.setBackground(new java.awt.Color(187, 187, 187));
        txtIdPaciente.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(108, 216, 158));
        jLabel2.setText("Nombres*");

        txtNombrePaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtNombrePaciente.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(108, 216, 158));
        jLabel3.setText("Apellidos*");

        txtApellidoPaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoPaciente.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(108, 216, 158));
        jLabel4.setText("Fecha Nacimiento");

        txtFNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        txtFNacimiento.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(108, 216, 158));
        jLabel5.setText("Ciudad Nacimiento");

        txtCNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        txtCNacimiento.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(108, 216, 158));
        jLabel6.setText("Dpto Nacimiento");

        txtDNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        txtDNacimiento.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(108, 216, 158));
        jLabel7.setText("Dirección");

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(108, 216, 158));
        jLabel8.setText("Tipo Documento");

        txtTipoDoc.setBackground(new java.awt.Color(255, 255, 255));
        txtTipoDoc.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(108, 216, 158));
        jLabel9.setText("Num Documento");

        txtNumDoc.setBackground(new java.awt.Color(255, 255, 255));
        txtNumDoc.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(108, 216, 158));
        jLabel10.setText("Email");

        txtEmailPaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailPaciente.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(108, 216, 158));
        jLabel11.setText("Sexo");

        txtSexo.setBackground(new java.awt.Color(255, 255, 255));
        txtSexo.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(108, 216, 158));
        jLabel12.setText("RH");

        txtRH.setBackground(new java.awt.Color(255, 255, 255));
        txtRH.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(108, 216, 158));
        jLabel13.setText("Gestante");

        comboGestante.setBackground(new java.awt.Color(255, 255, 255));
        comboGestante.setForeground(new java.awt.Color(37, 51, 61));
        comboGestante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "SI", "NO" }));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(108, 216, 158));
        jLabel14.setText("Programa de P y DT");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(108, 216, 158));
        jLabel15.setText("Etnia");

        comboEtnia.setBackground(new java.awt.Color(255, 255, 255));
        comboEtnia.setForeground(new java.awt.Color(37, 51, 61));
        comboEtnia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "Arhuaco", "Kogui", "Wiwa" }));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(108, 216, 158));
        jLabel16.setText("Fecha de Creación");

        txtFCreacion.setBackground(new java.awt.Color(255, 255, 255));
        txtFCreacion.setToolTipText("");

        btnSaveP.setBackground(new java.awt.Color(108, 216, 158));
        btnSaveP.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSaveP.setForeground(new java.awt.Color(37, 51, 61));
        btnSaveP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save_20px.png"))); // NOI18N
        btnSaveP.setText("Guardar");
        btnSaveP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(108, 216, 158));
        jLabel19.setText("Asociar Huella*");

        btnAssociate.setBackground(new java.awt.Color(108, 216, 158));
        btnAssociate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAssociate.setForeground(new java.awt.Color(37, 51, 61));
        btnAssociate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in_finger_20px.png"))); // NOI18N
        btnAssociate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssociateActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(37, 51, 61));

        btnNewP.setBackground(new java.awt.Color(108, 216, 158));
        btnNewP.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnNewP.setForeground(new java.awt.Color(37, 51, 61));
        btnNewP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_user_20px.png"))); // NOI18N
        btnNewP.setText("Nuevo");
        btnNewP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPActionPerformed(evt);
            }
        });

        btnIdentify.setBackground(new java.awt.Color(108, 216, 158));
        btnIdentify.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnIdentify.setForeground(new java.awt.Color(37, 51, 61));
        btnIdentify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerprint_20px.png"))); // NOI18N
        btnIdentify.setText("Identificar");
        btnIdentify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdentifyActionPerformed(evt);
            }
        });

        btnSearchUpdateP.setBackground(new java.awt.Color(108, 216, 158));
        btnSearchUpdateP.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSearchUpdateP.setForeground(new java.awt.Color(37, 51, 61));
        btnSearchUpdateP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_20px.png"))); // NOI18N
        btnSearchUpdateP.setText("Buscar y Actualizar");
        btnSearchUpdateP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUpdatePActionPerformed(evt);
            }
        });

        btnDeleteP.setBackground(new java.awt.Color(108, 216, 158));
        btnDeleteP.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnDeleteP.setForeground(new java.awt.Color(37, 51, 61));
        btnDeleteP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_user_20px.png"))); // NOI18N
        btnDeleteP.setText("Eliminar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(btnSearchUpdateP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIdentify, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNewP)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteP)
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnNewP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIdentify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearchUpdateP)
                .addComponent(btnDeleteP))
        );

        txtPYDT.setEditable(false);
        txtPYDT.setBackground(new java.awt.Color(187, 187, 187));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFNacimiento)
                            .addComponent(txtApellidoPaciente)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 2, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDNacimiento)
                            .addComponent(txtCNacimiento)
                            .addComponent(btnAssociate, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSaveP)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRH, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtSexo)
                            .addComponent(txtEmailPaciente)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTipoDoc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNumDoc, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboGestante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboEtnia, javax.swing.GroupLayout.Alignment.TRAILING, 0, 180, Short.MAX_VALUE)
                                    .addComponent(txtPYDT, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(1, 1, 1))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboGestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(comboEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtApellidoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(txtPYDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtEmailPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txtFCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAssociate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSaveP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        jPanel3.setBackground(new java.awt.Color(37, 51, 61));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 216, 158)));

        tableP.setBackground(new java.awt.Color(255, 255, 255));
        tableP.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID paciente", "Nombre ", "Apellido", "Fecha Nacimiento", "Ciudad Origen", "Dpto Origen", "Dirección", "Tipo Documento", "Num Documeto", "Email", "Sexo", "RH", "Gestante", "Etnia", "Programas PyDT", "Fecha de Creación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //tratando de listar al iniciar

    //método del botón Asociar Huella
    public void asociate() {

        //btnSearchUpdateOff();
        //btnSaveP.setEnabled(false);
        disableButtons(false, false, false);

        if (isOpen == false) {
            FormEnterFinger asociarHuella = new FormEnterFinger(this);
            asociarHuella.setVisible(true);
            isOpen = true;

        } else {

            //toaster.error("¡Nombre de usuario o contraseña inválidos!");
            JOptionPane.showMessageDialog(null, "Ya hay una ventana del 'Lector de Huellas' abierta", "Lector en Uso", JOptionPane.WARNING_MESSAGE);
            btnSearchUpdateOn();

        }

    }

    public void saveP() {
        clearTable();
        
        if (emptyFields()) {
            //btnSearchUpdateOn();
            if (tipoQuery) {
                Insert();
                txtNombrePaciente.requestFocus();

            } else {
                Update();
                tipoQuery = true;
            }

            clearFields();
            isOpen = false;
            //emptyFields();
            //btnAsociarOn();
            disableButtons(false, true, true);
        }
    }

    public void searchUpdate() {
        clearTable();
        //emptyFields();
        String nombreBuscar = JOptionPane.showInputDialog(null, "Ingresa un nombre o parte de él", "Búsqueda de Pacientes", QUESTION_MESSAGE);

        if (nombreBuscar != null) {
            if (nombreBuscar.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No se ingresó una coincidencia a buscar","Búsqueda Cancelada",JOptionPane.ERROR_MESSAGE);
            } else {

                Conexion cn = new Conexion();
                Connection cnn = cn.getConnection();
                try {
                    PreparedStatement ps = cnn.prepareStatement("SELECT * FROM paciente WHERE nombre_paciente LIKE '%" + nombreBuscar + "%'");

                    ResultSet rs = ps.executeQuery();

                    while (rs.next()) {

//                            if (rs.getString("nombre_paciente").equals(nombreBuscar)) {
//                                id_paciente = rs.getInt("id_paciente");
//                                tipoQuery = false;
//                                txtNombrePaciente.setText(rs.getString("nombre_paciente"));
//                                txtIdPaciente.setText(rs.getString("id_paciente"));
//                                disableButtons(false, true, false);
//                            }
                        modt.addRow(new Object[]{
                            rs.getInt("id_paciente"),
                            rs.getString("nombre_paciente")

                        });
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(FormPatients.class.getName()).log(Level.SEVERE, null, ex);
                    //JOptionPane.showMessageDialog(this, "El paciente NO está registrado en RUIPI","NO HAY REGISTRO", JOptionPane.ERROR_MESSAGE);

                }
            }
        }

    }

    public void identify() {

        System.out.println(isOpen);
        if (isOpen == false) {
            new FormIdentify(this).setVisible(true);

            isOpen = true;
        } else {

            //toaster.error("¡Nombre de usuario o contraseña inválidos!");
            JOptionPane.showMessageDialog(null, "Ya hay una ventana del 'Lector de Huellas' abierta", "Lector en Uso", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * @return the huellaPaciente
     */
    public ByteArrayInputStream getHuellaPaciente() {
        return huellaPaciente;
    }

    /**
     * @param huellaPaciente the huellaPaciente to set
     */
    public void setHuellaPaciente(ByteArrayInputStream huellaPaciente) {
        this.huellaPaciente = huellaPaciente;
    }

    public void clearTable() {
        int rows = tableP.getRowCount();
        for (int i = 0; i < rows; i++) {
            modt.removeRow(0);
        }
    }

    public void findP(int id) {

        Conexion cn = new Conexion();
        Connection cnn = cn.getConnection();
        try {
            PreparedStatement ps = cnn.prepareStatement("SELECT * FROM Paciente WHERE id_paciente=?");

            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                if (rs.getInt("id_paciente") == id) {
                    id_paciente = rs.getInt("id_paciente");
                    tipoQuery = false;
                    txtNombrePaciente.setText(rs.getString("nombre_paciente"));
                    txtIdPaciente.setText(rs.getString("id_paciente"));
                    disableButtons(false, true, false);
                }

            }

        } catch (SQLException ex) {
            Logger.getLogger(FormPatients.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(this, "El paciente NO está registrado en RUIPI","NO HAY REGISTRO", JOptionPane.ERROR_MESSAGE);

        }

    }

    public Integer getSizeHUella() {
        return sizeHuella;
    }

    public void setSizeHuella(Integer size) {
        sizeHuella = size;
    }

    private void setQueryInsert() {
        tipoQuery = true;
    }

    private void Insert() {

        Conexion cn = new Conexion();
        Connection cnn = cn.getConnection();
        //poner el if con em Jopane message
        try {
            System.out.println("INSERT");
            PreparedStatement ps = cnn.prepareStatement("INSERT INTO Paciente (huella, nombre_paciente) VALUES(?,?)");
            ps.setBinaryStream(1, huellaPaciente, sizeHuella);
            ps.setString(2, txtNombrePaciente.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "El paciente '" + txtNombrePaciente.getText() + "' se guardó con éxito","Paciente Registrado en RUIPI", JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        } catch (SQLException ex) {
            Logger.getLogger(FormPatients.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void Update() {
        Conexion cn = new Conexion();
        Connection cnn = cn.getConnection();

        if ("".equals(txtNombrePaciente.getText()) && huellaPaciente == null) {

            JOptionPane.showMessageDialog(null, "Los campos con * son obligatorios");

        } else {

            try {

                System.out.println("UPDATE");
                PreparedStatement ps = cnn.prepareStatement("UPDATE Paciente SET huella=?, nombre_paciente=? WHERE id_paciente=?");
                ps.setBinaryStream(1, huellaPaciente, sizeHuella);
                ps.setString(2, txtNombrePaciente.getText());
                ps.setInt(3, id_paciente);
                ps.execute();
                JOptionPane.showMessageDialog(null, "La actualización del paciente '" + txtNombrePaciente.getText() + "' se guardó con éxito","Paciente Actualizado",JOptionPane.INFORMATION_MESSAGE);
                clearFields();
            } catch (SQLException ex) {
                Logger.getLogger(FormPatients.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }

    public boolean emptyFields() {

        if (txtNombrePaciente.getText().isEmpty() || huellaPaciente == null) {
            JOptionPane.showMessageDialog(null, "No pueden haber campos vacíos", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            txtNombrePaciente.requestFocus();
            return false;

        } else {
            btnSaveP.setEnabled(true);
            return true;

        }

    }

    public void btnAsociarOff() {

        btnAssociate.setEnabled(false);
    }

    public void btnAsociarOn() {

        btnAssociate.setEnabled(true);
    }

    public void btnSearchUpdateOff() {

        btnSearchUpdateP.setEnabled(false);
    }

    public void btnSearchUpdateOn() {

        btnSearchUpdateP.setEnabled(true);
    }

    public void btnSavePOn() {
        btnSaveP.setEnabled(true);
    }

    public void btnSavePOff() {
        btnSaveP.setEnabled(false);
    }

    public void clearFields() {

        txtIdPaciente.setText("");
        txtNombrePaciente.setText("");
        txtApellidoPaciente.setText("");
        txtFNacimiento.setText("");
        txtCNacimiento.setText("");
        txtDNacimiento.setText("");
        txtDireccion.setText("");
        txtTipoDoc.setText("");
        txtNumDoc.setText("");
        txtEmailPaciente.setText("");
        txtSexo.setText("");
        txtRH.setText("");
        comboGestante.setSelectedIndex(0);
        comboEtnia.setSelectedIndex(0);
        //txtComunidad.setText("");
        //txtMunicipio.setText("");
        txtPYDT.setText("");
        huellaPaciente = null;
        //btnSavePOff();
        setQueryInsert();
        clearTable();
        disableButtons(false, true, true);//1/10/2020/5:36pm
    }

    public void disableButtons(boolean save, boolean search, boolean identify) {
        btnSaveP.setEnabled(save);
        btnSearchUpdateP.setEnabled(search);
        btnIdentify.setEnabled(identify);
    }


    private void btnAssociateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssociateActionPerformed
        asociate();
    }//GEN-LAST:event_btnAssociateActionPerformed

    private void btnSavePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePActionPerformed
        saveP();
    }//GEN-LAST:event_btnSavePActionPerformed

    private void btnSearchUpdatePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUpdatePActionPerformed
        searchUpdate();
    }//GEN-LAST:event_btnSearchUpdatePActionPerformed

    private void btnIdentifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdentifyActionPerformed
        identify();
    }//GEN-LAST:event_btnIdentifyActionPerformed

    private void btnNewPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPActionPerformed
        clearFields();
        //disableButtons(false, true, true);
    }//GEN-LAST:event_btnNewPActionPerformed

    private void tablePMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePMouseClicked
        if (evt.getClickCount() == 2) {

            txtIdPaciente.setText((tableP.getValueAt(tableP.getSelectedRow(), 0).toString()));
            id_paciente=Integer.valueOf(txtIdPaciente.getText());
            txtNombrePaciente.setText((tableP.getValueAt(tableP.getSelectedRow(), 1).toString()));
            
            tipoQuery = false;
            disableButtons(false, true, false);
        }
    }//GEN-LAST:event_tablePMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAssociate;
    public javax.swing.JButton btnDeleteP;
    public javax.swing.JButton btnIdentify;
    public javax.swing.JButton btnNewP;
    public javax.swing.JButton btnSaveP;
    public javax.swing.JButton btnSearchUpdateP;
    public javax.swing.JComboBox<String> comboEtnia;
    public javax.swing.JComboBox<String> comboGestante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableP;
    public javax.swing.JTextField txtApellidoPaciente;
    public javax.swing.JTextField txtCNacimiento;
    public javax.swing.JTextField txtDNacimiento;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtEmailPaciente;
    public javax.swing.JTextField txtFCreacion;
    public javax.swing.JTextField txtFNacimiento;
    public javax.swing.JTextField txtIdPaciente;
    public javax.swing.JTextField txtNombrePaciente;
    public javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtPYDT;
    public javax.swing.JTextField txtRH;
    public javax.swing.JTextField txtSexo;
    public javax.swing.JTextField txtTipoDoc;
    // End of variables declaration//GEN-END:variables

}
