/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Connector.Conexion;
import Toaster.Toaster;
import java.sql.*;
import java.io.ByteArrayInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;

/**
 *
 * @author lenov
 */
public class formPatients extends javax.swing.JInternalFrame {

    private ByteArrayInputStream huellaPaciente;
    Integer sizeHuella;
    boolean isOpen = false;
    boolean tipoQuery = false;
    Toaster toaster;
    int id_paciente;

    public formPatients() {
        setQueryInsert();
        initComponents();
        txtNombrePaciente.requestFocus(); //NO CAMBIA EL FOCO AL txtNombrePaciente!!!
        //toaster = new Toaster(new JPanel);    MODIFICAR!!
        emptyFields();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdPaciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombrePaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoPaaciente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFNacimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCNacimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDNacimiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTipoDoc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmailPaciente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRH = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        comboGestante = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFCreacion = new javax.swing.JTextField();
        btnSaveP = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        btnAssociate = new javax.swing.JButton();
        comboEtnia = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnDeleteP = new javax.swing.JButton();
        btnIdentify = new javax.swing.JButton();
        btnSearchUpdateP = new javax.swing.JButton();
        btnClearP = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableP = new javax.swing.JTable();

        setBackground(new java.awt.Color(37, 51, 61));
        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gestión de Pacientes");
        setMinimumSize(new java.awt.Dimension(800, 450));

        jPanel1.setBackground(new java.awt.Color(37, 51, 61));

        jPanel2.setBackground(new java.awt.Color(37, 51, 61));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 216, 158), 1, true));
        jPanel2.setToolTipText("");
        jPanel2.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 216, 158));
        jLabel1.setText("ID Paciente");

        txtIdPaciente.setEditable(false);
        txtIdPaciente.setBackground(new java.awt.Color(187, 187, 187));
        txtIdPaciente.setToolTipText("");
        txtIdPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPacienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(108, 216, 158));
        jLabel2.setText("Nombres*");

        txtNombrePaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtNombrePaciente.setToolTipText("");
        txtNombrePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePacienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(108, 216, 158));
        jLabel3.setText("Apellidos*");

        txtApellidoPaaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoPaaciente.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(108, 216, 158));
        jLabel4.setText("Fecha Nacimiento");

        txtFNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        txtFNacimiento.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(108, 216, 158));
        jLabel5.setText("Ciudad Nacimiento");

        txtCNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        txtCNacimiento.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(108, 216, 158));
        jLabel6.setText("Dpto Nacimiento");

        txtDNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        txtDNacimiento.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(108, 216, 158));
        jLabel7.setText("Dirección");

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(108, 216, 158));
        jLabel8.setText("Tipo Documento");

        txtTipoDoc.setBackground(new java.awt.Color(255, 255, 255));
        txtTipoDoc.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(108, 216, 158));
        jLabel9.setText("Num Documento");

        txtNumDoc.setBackground(new java.awt.Color(255, 255, 255));
        txtNumDoc.setToolTipText("");
        txtNumDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumDocActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(108, 216, 158));
        jLabel10.setText("Email");

        txtEmailPaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailPaciente.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(108, 216, 158));
        jLabel11.setText("Sexo");

        txtSexo.setBackground(new java.awt.Color(255, 255, 255));
        txtSexo.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(108, 216, 158));
        jLabel12.setText("RH");

        txtRH.setBackground(new java.awt.Color(255, 255, 255));
        txtRH.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(108, 216, 158));
        jLabel13.setText("Gestante");

        comboGestante.setBackground(new java.awt.Color(255, 255, 255));
        comboGestante.setForeground(new java.awt.Color(37, 51, 61));
        comboGestante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "SI", "NO" }));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(108, 216, 158));
        jLabel14.setText("Edad");

        txtEdad.setBackground(new java.awt.Color(255, 255, 255));
        txtEdad.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(108, 216, 158));
        jLabel15.setText("Etnia");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(108, 216, 158));
        jLabel16.setText("Fecha de Creación");

        txtFCreacion.setBackground(new java.awt.Color(255, 255, 255));
        txtFCreacion.setToolTipText("");

        btnSaveP.setBackground(new java.awt.Color(108, 216, 158));
        btnSaveP.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSaveP.setForeground(new java.awt.Color(37, 51, 61));
        btnSaveP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save_20px.png"))); // NOI18N
        btnSaveP.setText("Guardar");
        btnSaveP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(108, 216, 158));
        jLabel19.setText("Asociar Huella*");

        btnAssociate.setBackground(new java.awt.Color(108, 216, 158));
        btnAssociate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAssociate.setForeground(new java.awt.Color(37, 51, 61));
        btnAssociate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in_finger_20px.png"))); // NOI18N
        btnAssociate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssociateActionPerformed(evt);
            }
        });

        comboEtnia.setBackground(new java.awt.Color(255, 255, 255));
        comboEtnia.setForeground(new java.awt.Color(37, 51, 61));
        comboEtnia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "Arhuaco", "Kogui", "Wiwa" }));

        jPanel4.setBackground(new java.awt.Color(37, 51, 61));

        btnDeleteP.setBackground(new java.awt.Color(108, 216, 158));
        btnDeleteP.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnDeleteP.setForeground(new java.awt.Color(37, 51, 61));
        btnDeleteP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_user_20px.png"))); // NOI18N
        btnDeleteP.setText("Eliminar");

        btnIdentify.setBackground(new java.awt.Color(108, 216, 158));
        btnIdentify.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnIdentify.setForeground(new java.awt.Color(37, 51, 61));
        btnIdentify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerprint_20px.png"))); // NOI18N
        btnIdentify.setText("Identificar");
        btnIdentify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdentifyActionPerformed(evt);
            }
        });

        btnSearchUpdateP.setBackground(new java.awt.Color(108, 216, 158));
        btnSearchUpdateP.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSearchUpdateP.setForeground(new java.awt.Color(37, 51, 61));
        btnSearchUpdateP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_20px.png"))); // NOI18N
        btnSearchUpdateP.setText("Buscar y Actualizar");
        btnSearchUpdateP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUpdatePActionPerformed(evt);
            }
        });

        btnClearP.setBackground(new java.awt.Color(108, 216, 158));
        btnClearP.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnClearP.setForeground(new java.awt.Color(37, 51, 61));
        btnClearP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear_20px.png"))); // NOI18N
        btnClearP.setText("Limpiar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(btnSearchUpdateP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIdentify, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearP)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnDeleteP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIdentify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearchUpdateP)
                .addComponent(btnClearP))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFNacimiento)
                            .addComponent(txtApellidoPaaciente)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 2, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDNacimiento)
                            .addComponent(txtCNacimiento)
                            .addComponent(btnAssociate, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSaveP)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRH, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtSexo)
                            .addComponent(txtEmailPaciente)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTipoDoc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNumDoc, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(comboGestante, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboEtnia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboGestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellidoPaaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(comboEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtEmailPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txtFCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAssociate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSaveP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(37, 51, 61));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 216, 158)));

        tableP.setBackground(new java.awt.Color(255, 255, 255));
        tableP.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID paciente", "Huella", "Nombre ", "Apellido", "Fecha Nacimiento", "Ciudad Origen", "Dpto Origen", "Dirección", "Tipo Documento", "Num Documeto", "Email", "Sexo", "RH", "Gestante", "Edad", "Etnia", "Fecha de Creación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableP);
        if (tableP.getColumnModel().getColumnCount() > 0) {
            tableP.getColumnModel().getColumn(14).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumDocActionPerformed

    private void txtIdPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPacienteActionPerformed

    private void btnAssociateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssociateActionPerformed
        emptyFields();
        btnSearchUpdateOff();
        btnSaveP.setEnabled(false);
        
        if (isOpen == false) {
            formEnterFinger asociarHuella = new formEnterFinger(this);
            asociarHuella.setVisible(true);
            isOpen = true;
            
            
        } else {

            //toaster.error("¡Nombre de usuario o contraseña inválidos!");
            JOptionPane.showMessageDialog(null, "Ya hay una ventana del 'Lector de Huellas' abierta");
        }
       
        
    }//GEN-LAST:event_btnAssociateActionPerformed

    private void btnSavePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePActionPerformed
        btnSearchUpdateOn();    
        
        if (tipoQuery) {
            Insert();

        } else {
            Update();
            tipoQuery = true;
        }
        txtNombrePaciente.setText("");
        id_paciente = 0;
        huellaPaciente=null;
        isOpen = false;
        emptyFields();
        btnAsociarOn();
        
    }//GEN-LAST:event_btnSavePActionPerformed


    private void btnIdentifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdentifyActionPerformed
        System.out.println(isOpen);
        if (isOpen == false) {
            new formIdentifity(this).setVisible(true);

            isOpen = true;
        } else {

            //toaster.error("¡Nombre de usuario o contraseña inválidos!");
            JOptionPane.showMessageDialog(null, "Ya hay una ventana del 'Lector de Huellas' abierta");
        }

    }//GEN-LAST:event_btnIdentifyActionPerformed

    private void btnSearchUpdatePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUpdatePActionPerformed
        //emptyFields();
        
        String nombreBuscar = JOptionPane.showInputDialog(null, "Nombre o ID del paciente", "BÚSQUEDA DE PACIENTES", QUESTION_MESSAGE );

        Conexion cn = new Conexion();
        Connection cnn = cn.getConnection();
        try {
            PreparedStatement ps = cnn.prepareStatement("SELECT * FROM Paciente WHERE nombre_paciente=?");

            ps.setString(1, nombreBuscar);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                if (rs.getString("nombre_paciente").equals(nombreBuscar)) {
                    id_paciente = rs.getInt("id_paciente");
                    tipoQuery = false;
                    txtNombrePaciente.setText(rs.getString("nombre_paciente"));

                }

            }

        } catch (SQLException ex) {
            Logger.getLogger(formPatients.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchUpdatePActionPerformed

    private void txtNombrePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePacienteActionPerformed
            }//GEN-LAST:event_txtNombrePacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAssociate;
    public javax.swing.JButton btnClearP;
    public javax.swing.JButton btnDeleteP;
    public javax.swing.JButton btnIdentify;
    public javax.swing.JButton btnSaveP;
    public javax.swing.JButton btnSearchUpdateP;
    public javax.swing.JComboBox<String> comboEtnia;
    public javax.swing.JComboBox<String> comboGestante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableP;
    public javax.swing.JTextField txtApellidoPaaciente;
    public javax.swing.JTextField txtCNacimiento;
    public javax.swing.JTextField txtDNacimiento;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtEmailPaciente;
    public javax.swing.JTextField txtFCreacion;
    public javax.swing.JTextField txtFNacimiento;
    public javax.swing.JTextField txtIdPaciente;
    public javax.swing.JTextField txtNombrePaciente;
    public javax.swing.JTextField txtNumDoc;
    public javax.swing.JTextField txtRH;
    public javax.swing.JTextField txtSexo;
    public javax.swing.JTextField txtTipoDoc;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the huellaPaciente
     */
    public ByteArrayInputStream getHuellaPaciente() {
        return huellaPaciente;
    }

    /**
     * @param huellaPaciente the huellaPaciente to set
     */
    public void setHuellaPaciente(ByteArrayInputStream huellaPaciente) {
        this.huellaPaciente = huellaPaciente;
    }

    public Integer getSizeHUella() {
        return sizeHuella;
    }

    public void setSizeHuella(Integer size) {
        sizeHuella = size;
    }

    private void setQueryInsert() {
        tipoQuery = true;
    }

    private void Insert() {
        Conexion cn = new Conexion();
        Connection cnn = cn.getConnection();
        //poner el if con em Jopane message
        try {
            System.out.println("INSERT");
            PreparedStatement ps = cnn.prepareStatement("INSERT INTO Paciente (huella, nombre_paciente) VALUES(?,?)");
            ps.setBinaryStream(1, huellaPaciente, sizeHuella);
            ps.setString(2, txtNombrePaciente.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "El registro del paciente '" + txtNombrePaciente.getText() + "' se guardó con éxito.");
        } catch (SQLException ex) {
            Logger.getLogger(formPatients.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void Update() {
        Conexion cn = new Conexion();
        Connection cnn = cn.getConnection();

        if ("".equals(txtNombrePaciente.getText())) {

            JOptionPane.showMessageDialog(null, "Los campos con '*' son obligatorios");
        } else {

            try {

                System.out.println("UPDATE");
                PreparedStatement ps = cnn.prepareStatement("UPDATE Paciente SET huella=? WHERE id_paciente=?");
                ps.setBinaryStream(1, huellaPaciente, sizeHuella);
                ps.setInt(2, id_paciente);
                ps.execute();
                JOptionPane.showMessageDialog(null, "La actualización del paciente '" + txtNombrePaciente.getText() + "' se guardó con éxito.");
            } catch (SQLException ex) {
                Logger.getLogger(formPatients.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }

    public void emptyFields() {
        boolean i = true;
        if (i) {
            try {
                if ("".equals(txtNombrePaciente.getText())) {
                    btnSaveP.setEnabled(false);
                    
                } else {
                    btnSaveP.setEnabled(true);
                    i = false;
                    
                }

            } catch (Exception e) {
            }
        }
    }
    
    public void btnAsociarOff(){
        
        btnAssociate.setEnabled(false);
    }
    
    public void btnAsociarOn(){
        
        btnAssociate.setEnabled(true);
    }
    
     public void btnSearchUpdateOff(){
        
        btnSearchUpdateP.setEnabled(false);
    }
    
    public void btnSearchUpdateOn(){
        
        btnSearchUpdateP.setEnabled(true);
    }
}

